name: bcs_one_android
description: "A new Flutter project for BCS One."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  supabase_flutter: ^2.5.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  app_links: 6.3.0
